apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: default
  name: pods4logs
  labels:
    app: logsdemo
    tier: logsdemo
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: logsdemo
  template:
    metadata:
      labels:
        tier: logsdemo
    spec:
      containers:
      - name: generatelogs
        image: quay.io/rhn_support_nwaizer/get_pod_logs_efficiently
