apiVersion: apps/v1
kind: Deployment
metadata:
  name: pods4logs
  namespace: default
  labels:
    app: logsdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: logsdemo
  template:
    metadata:
      labels:
        app: logsdemo
    spec:
      containers:
      - name: generatelogs
        image: quay.io/rhn_support_nwaizer/get_pod_logs_efficiently
